#
# This file is auto-generated. DO NOT EDIT
# Generated by: autospec.py
# Using build pattern: R
# autospec version: v21
# autospec commit: f4a13a5
#
Name     : R-lsei
Version  : 1.3.0
Release  : 43
URL      : https://cran.r-project.org/src/contrib/lsei_1.3-0.tar.gz
Source0  : https://cran.r-project.org/src/contrib/lsei_1.3-0.tar.gz
Summary  : Solving Least Squares or Quadratic Programming Problems under
Group    : Development/Tools
License  : GPL-2.0+
Requires: R-lsei-lib = %{version}-%{release}
BuildRequires : buildreq-R
# Suppress stripping binaries
%define __strip /bin/true
%define debug_package %{nil}

%description
regression problems under linear equality/inequality
	     constraints. Functions for solving quadratic programming
	     problems are also available, which transform such problems
	     into least squares ones first. It is developed based on the
	     'Fortran' program of Lawson and Hanson (1974, 1995), which is
	     public domain and available at

%package lib
Summary: lib components for the R-lsei package.
Group: Libraries

%description lib
lib components for the R-lsei package.


%prep
%setup -q -n lsei
pushd ..
cp -a lsei buildavx2
popd
pushd ..
cp -a lsei buildavx512
popd

%build
export http_proxy=http://127.0.0.1:9/
export https_proxy=http://127.0.0.1:9/
export no_proxy=localhost,127.0.0.1,0.0.0.0
export LANG=C.UTF-8
export SOURCE_DATE_EPOCH=1737150401

%install
export SOURCE_DATE_EPOCH=1737150401
rm -rf %{buildroot}
LANG=C.UTF-8
CFLAGS="$CLEAR_INTERMEDIATE_CFLAGS -O3 -flto -fno-semantic-interposition "
FCFLAGS="$CLEAR_INTERMEDIATE_FFLAGS -O3 -flto -fno-semantic-interposition "
FFLAGS="$CLEAR_INTERMEDIATE_FFLAGS -O3 -flto -fno-semantic-interposition "
CXXFLAGS="$CLEAR_INTERMEDIATE_CXXFLAGS -O3 -flto -fno-semantic-interposition "
AR=gcc-ar
RANLIB=gcc-ranlib
LDFLAGS="$CLEAR_INTERMEDIATE_LDFLAGS  -Wl,-z -Wl,relro"
mkdir -p %{buildroot}/usr/lib64/R/library
mkdir -p %{buildroot}-v3/usr/lib64/R/library
mkdir -p %{buildroot}-v4/usr/lib64/R/library
mkdir -p %{buildroot}-va/usr/lib64/R/library

mkdir -p ~/.R
echo "CFLAGS = $CFLAGS -march=x86-64-v3 -ftree-vectorize -mno-vzeroupper" > ~/.R/Makevars
echo "FFLAGS = $FFLAGS -march=x86-64-v3 -ftree-vectorize -mno-vzeroupper " >> ~/.R/Makevars
echo "CXXFLAGS = $CXXFLAGS -march=x86-64-v3 -ftree-vectorize -mno-vzeroupper " >> ~/.R/Makevars
R CMD INSTALL  --install-tests --use-LTO --built-timestamp=${SOURCE_DATE_EPOCH} --data-compress=none --compress=none --build  -l %{buildroot}-v3/usr/lib64/R/library .
echo "CFLAGS = $CFLAGS -march=x86-64-v4 -mprefer-vector-width=512 -ftree-vectorize  -mno-vzeroupper " > ~/.R/Makevars
echo "FFLAGS = $FFLAGS -march=x86-64-v4 -mprefer-vector-width=512 -ftree-vectorize  -mno-vzeroupper " >> ~/.R/Makevars
echo "CXXFLAGS = $CXXFLAGS -march=x86-64-v4 -mprefer-vector-width=512 -ftree-vectorize -mno-vzeroupper " >> ~/.R/Makevars
R CMD INSTALL --preclean  --install-tests --use-LTO --no-test-load --data-compress=none --compress=none --built-timestamp=${SOURCE_DATE_EPOCH} --build  -l %{buildroot}-v4/usr/lib64/R/library .
echo "CFLAGS = $CFLAGS -ftree-vectorize " > ~/.R/Makevars
echo "FFLAGS = $FFLAGS -ftree-vectorize " >> ~/.R/Makevars
echo "CXXFLAGS = $CXXFLAGS -ftree-vectorize " >> ~/.R/Makevars
R CMD INSTALL --preclean  --use-LTO --install-tests --data-compress=none --compress=none --built-timestamp=${SOURCE_DATE_EPOCH} --build  -l %{buildroot}/usr/lib64/R/library .
%{__rm} -rf %{buildroot}%{_datadir}/R/library/R.css
%check
export LANG=C.UTF-8
export http_proxy=http://127.0.0.1:9/
export https_proxy=http://127.0.0.1:9/
export no_proxy=localhost,127.0.0.1,0.0.0.0
export _R_CHECK_FORCE_SUGGESTS_=false
R CMD check --no-manual --no-examples --no-codoc . || :

/usr/bin/elf-move.py avx2 %{buildroot}-v3 %{buildroot} %{buildroot}/usr/share/clear/filemap/filemap-%{name}
/usr/bin/elf-move.py avx512 %{buildroot}-v4 %{buildroot} %{buildroot}/usr/share/clear/filemap/filemap-%{name}

%files
%defattr(-,root,root,-)
/usr/lib64/R/library/lsei/DESCRIPTION
/usr/lib64/R/library/lsei/INDEX
/usr/lib64/R/library/lsei/Meta/Rd.rds
/usr/lib64/R/library/lsei/Meta/features.rds
/usr/lib64/R/library/lsei/Meta/hsearch.rds
/usr/lib64/R/library/lsei/Meta/links.rds
/usr/lib64/R/library/lsei/Meta/nsInfo.rds
/usr/lib64/R/library/lsei/Meta/package.rds
/usr/lib64/R/library/lsei/NAMESPACE
/usr/lib64/R/library/lsei/R/lsei
/usr/lib64/R/library/lsei/R/lsei.rdb
/usr/lib64/R/library/lsei/R/lsei.rdx
/usr/lib64/R/library/lsei/help/AnIndex
/usr/lib64/R/library/lsei/help/aliases.rds
/usr/lib64/R/library/lsei/help/lsei.rdb
/usr/lib64/R/library/lsei/help/lsei.rdx
/usr/lib64/R/library/lsei/help/paths.rds
/usr/lib64/R/library/lsei/html/00Index.html
/usr/lib64/R/library/lsei/html/R.css

%files lib
%defattr(-,root,root,-)
/V3/usr/lib64/R/library/lsei/libs/lsei.so
/V4/usr/lib64/R/library/lsei/libs/lsei.so
/usr/lib64/R/library/lsei/libs/lsei.so
